[package]
name = "dfrs_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
colored = "2.1.0"
dfrs_core = { path = "../core" }
